language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
notifications:
  email:
    recipients:
      - delciotorres+travisci@gmail.com
    on_success: change
    on_failure: change
  #slack:
  #  on_success: change
  #  on_failure: change
  #  rooms:
  #    - secure:
